[build]
# rustflags = ["-C", "target-cpu=native"]
# rustdocflags = ["-C", "target-cpu=native"]

[target.wasm32-unknown-unknown]
# rustflags = ["-C", "target-feature=+simd128"]

[target.wasm32-wasi]
# rustflags = ["-C", "target-feature=+simd128"]

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
